### ISSUE TITLE
Compatibility with lifetimes

### ISSUE THREAD

**Issue by NotSqrt** [daboross/serde-tuple-vec-map#2]
Hello,

I've been reading https://serde.rs/lifetimes.html, and I wonder what happens for something like:
```rust
#[derive(Serialize, Deserialize)]
struct MyStuff<'a> {
    #[serde(with = "tuple_vec_map")]
    data: Vec<(&'a str, ValueType)>,
}
```
Would serde-tuple-vec-map be able to borrow the keys as `&'de str` and avoid copies ?

Thanks a lot.

**Comment by daboross** [comment]
In general, this kind of thing should "just work"! `serde-tuple-vec-map` delegates the inner work to the inner types, and `&str` knows how to zero-copy deserialize.

In your particular example, you can be confident that if it compiles, then it will 100% work. The reason I say this is that `&str` has no "owned" form, so if it's deserialized, it is deserialized in a zero-copy way (borrowing from `'a`) - and if that can't happen, then you'll get a compile error.


In other cases, you might need a `#[serde(borrow)]` on the field to force serde to borrow. Particularly, types like `Cow<'a, str>` can be deserialized in either a borrowed or an owned form. So the additional `#[serde(borrow)]` gets serde_derive to give you a borrowed deserialize call.

**Comment by NotSqrt** [comment]
Thanks for your answer.

The `borrow` was the missing piece of the puzzle !
Without it, it did not compile.

```rust
#[derive(Serialize, Deserialize)]
struct MyStuff<'a> {
    #[serde(with = "tuple_vec_map", borrow)]
    data: Vec<(&'a str, ValueType)>,
}
```

Thanks !
