### ISSUE TITLE
Release a new version on crates.io

### ISSUE THREAD

**Issue by whentze** [daboross/serde-tuple-vec-map#3]
The last crates.io release, 0.2.1, does not build on recent rust because it uses the old `collections::` module instead of `alloc::`. This is fixed on master, but there hasn't been a release in a while.

Is it worth it to put out a new version?

**Comment by daboross** [comment]
Yes! Thanks for filing this. I'll push an update - didn't realize the latest changes weren't on crates.io.

**Comment by daboross** [comment]
Version 0.2.2 published!

I suppose it's probably also about time for a 1.0 version for this crate. All the dependencies are stable, and it's not the functionality is stable and well-tested enough.
