### ISSUE TITLE
Typo in default Vec capacity limitation

### ISSUE THREAD

**Issue by zheland** [daboross/serde-tuple-vec-map#4]
The maximum `Vec` capacity in `TupleVecMapVisitor::visit_map` is limited to 40**69**.
https://github.com/daboross/serde-tuple-vec-map/blob/794994a715a0d32647b079be6f8cc43f418ace88/src/lib.rs#L86

But it probably should be 40**96** as in the similar code from serde:
https://github.com/serde-rs/serde/blob/7e19ae8c9486a3bbbe51f1befb05edee94c454f9/serde/src/private/size_hint.rs#L13
```rust
    cmp::min(hint.unwrap_or(0), 4096)
```

**Comment by daboross** [comment]
Thanks! Fixed. I've released this as a point release since it's a minor change, not technically documented either way, and thus should only really effect performance.

**Comment by daboross** [comment]
First post-1.0 bugfix for this crate!
